name: Release Drafter

on: push

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Update Release
        id: update_release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-osx:
    runs-on: macos-latest
    needs: update_release_draft
    steps:
      - uses: actions/checkout@v1
      - name: Compile Binary
        run: ./scripts/build.sh
      - name: Pachage Application
        run: |
          go get fyne.io/fyne/cmd/fyne
          ./scripts/package.sh
      - name: Upload Application
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ jobs.update_release_draft.steps.update_release.outputs.upload_url }}
          asset_path: ./Dragoon-Editor.zip
          asset_name: Dragoon-Editor.zip
          asset_content_type: application/zip
