name: Release Drafter

on: push

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Compile Binary
        run: ./scripts/build.sh
      - name: Pachage Application
        run: ./scripts/package.sh
      - name: Upload Binary
        uses: actions/upload-artifact@master
        with:
          name: LODeditor.app
          path: .